use rand::seq::SliceRandom;

#[derive(Debug, Clone)]
pub struct PassphraseOptions {
    pub word_count: usize,
    pub separator: char,
    pub capitalize: bool,
}

impl Default for PassphraseOptions {
    fn default() -> Self {
        Self {
            word_count: 5,
            separator: '-',
            capitalize: false,
        }
    }
}

/// EFF large wordlist (7776 words). Embedded as a static array.
/// This is the EFF "Diceware" wordlist for passphrases.
/// For the full list we would include all 7776 words; here we use a representative subset
/// and the real implementation should load from the assets file or embed the full list.
const WORDLIST: &[&str] = &[
    "abacus", "abdomen", "abdominal", "abide", "abiding", "ability", "ablaze", "able",
    "abnormal", "abode", "about", "above", "abrupt", "absence", "absent", "absolve",
    "absorb", "abstain", "abstract", "absurd", "accent", "accept", "access", "accident",
    "acclaim", "acclimate", "accomplish", "account", "accuracy", "accurate", "accustom",
    "acetone", "achiness", "aching", "acid", "acorn", "acquaint", "acre", "acrid", "acrobat",
    "action", "activate", "activist", "actual", "acute", "adamant", "adapt", "add",
    "addicted", "addition", "adept", "adequate", "adjust", "admin", "admiral", "admire",
    "adolescent", "adopt", "adore", "adorn", "adult", "advance", "advocate", "aegis",
    "affair", "affect", "affirm", "afflict", "afford", "affront", "afoot", "after",
    "again", "against", "age", "agency", "agenda", "aggregate", "aghast", "agile",
    "aging", "agnostic", "agonize", "agree", "ahead", "aide", "aim", "air", "airport",
    "aisle", "alarm", "album", "alcohol", "alert", "alien", "align", "alike",
    "alive", "alkaline", "all", "alley", "alliance", "almost", "aloft", "alone",
    "along", "aloof", "alphabet", "already", "also", "alter", "always", "amaze",
    "ambush", "amend", "ample", "amuse", "anchor", "android", "angel", "angle",
    "angry", "angst", "animal", "ankle", "announce", "annual", "another", "answer",
    "antic", "anvil", "anybody", "anyhow", "anyone", "anyway", "anywhere", "apart",
    "apex", "aphid", "aplomb", "apple", "apply", "apricot", "aptitude", "aquarium",
    "arcade", "arch", "ardent", "arena", "argue", "arise", "armor", "aroma",
    "around", "arouse", "array", "arson", "ascend", "aside", "ask", "asleep",
    "aspect", "aspirin", "assault", "asset", "assist", "assume", "asthma", "athlete",
    "atlas", "atom", "atrium", "attach", "attic", "attitude", "auction", "augment",
    "aunt", "aura", "autism", "autumn", "avatar", "avid", "avoid", "awake",
    "award", "aware", "awful", "awkward", "awning", "awoke", "axial", "axis",
    "babble", "baby", "backbone", "backdrop", "backup", "bacon", "badge", "badly",
    "bag", "bail", "bait", "bake", "balance", "balcony", "ball", "ballet",
    "balloon", "ballot", "bamboo", "banana", "banner", "bar", "barbecue", "barge",
    "barn", "barrel", "base", "basin", "basket", "bass", "batch", "batten",
    "battle", "bay", "beacon", "beak", "beam", "bean", "bear", "beard",
    "beast", "beat", "bed", "bedroom", "beef", "beet", "before", "beg",
    "begin", "behalf", "behave", "behind", "belief", "belong", "below", "bench",
    "bend", "benefit", "bent", "best", "betray", "better", "between", "beyond",
    "bias", "bid", "bicycle", "bidet", "bifocals", "big", "bike", "bikini",
    "bill", "bird", "birth", "biscuit", "bite", "bitter", "black", "blade",
    "bland", "blank", "blast", "blatant", "bleach", "bleak", "bleat", "bleed",
    "blend", "bless", "blimp", "blind", "blink", "bliss", "blitz", "block",
    "bloke", "blond", "blood", "bloom", "blow", "blue", "bluff", "blunt",
    "blurt", "blush", "board", "boast", "boat", "body", "bogus", "bold",
    "bolt", "bomb", "bond", "bone", "book", "boom", "boost", "boot",
    "border", "bore", "born", "boss", "both", "bottle", "bottom", "bounce",
    "box", "brace", "brain", "brake", "branch", "brand", "brave", "bread",
    "break", "breed", "brick", "bride", "brief", "bright", "brim", "bring",
    "brisk", "broad", "broccoli", "broken", "broker", "bronze", "brood", "brook",
    "brother", "brush", "brute", "bubble", "bucket", "budget", "buffalo", "build",
    "bulb", "bulk", "bullet", "bully", "bump", "bunch", "bunny", "burden",
    "burger", "burial", "burn", "burrow", "burst", "bus", "business", "busy",
    "butter", "button", "buy", "buzz", "cable", "cactus", "cage", "cake",
    "calf", "call", "calm", "camera", "camp", "canal", "cancel", "candy",
    "canvas", "canyon", "cap", "capital", "capsule", "capture", "car", "carbon",
    "card", "care", "career", "cargo", "carpet", "carrot", "carry", "cart",
    "case", "cash", "cast", "castle", "casual", "catalog", "cat", "catch",
    "category", "cattle", "caught", "cause", "cavalry", "cease", "ceiling", "celery",
    "cement", "census", "ceramic", "certain", "chain", "chair", "chalk", "champion",
    "change", "chaos", "chapter", "charge", "chase", "cheap", "check", "cheek",
    "cheer", "cheese", "chef", "cherry", "chest", "chew", "chicken", "chief",
    "child", "chimney", "choice", "choir", "choose", "chop", "chrome", "chunk",
    "churn", "cider", "cigar", "cinema", "circle", "citizen", "city", "civil",
    "claim", "clap", "clarify", "claw", "clay", "clean", "clerk", "clever",
    "click", "client", "cliff", "climb", "cling", "clip", "clock", "clone",
    "close", "cloth", "cloud", "clown", "club", "cluck", "clue", "clump",
    "cluster", "clutch", "coach", "coast", "coat", "cobra", "cocoa", "coil",
    "coin", "cold", "collapse", "collect", "college", "collision", "colony", "color",
    "column", "combine", "come", "comfort", "comic", "comma", "common", "company",
    "concert", "conduct", "confirm", "connect", "consider", "control", "convince", "cook",
    "cool", "copper", "copy", "coral", "core", "corn", "corner", "correct",
    "cost", "couch", "count", "couple", "course", "cousin", "cover", "coyote",
    "crack", "cradle", "craft", "crane", "crash", "crawl", "crazy", "cream",
    "credit", "crew", "cricket", "crime", "crisp", "critic", "crop", "cross",
    "crowd", "crucial", "cruel", "crush", "cry", "crystal", "cubic", "culture",
    "cup", "cupboard", "curious", "current", "curtain", "curve", "cushion", "custom",
    "cute", "cycle", "dad", "damage", "damp", "dance", "danger", "daring",
    "dash", "daughter", "dawn", "day", "deal", "debate", "debris", "decade",
    "decide", "deck", "declare", "decline", "decorate", "decoy", "decrease", "dedicate",
    "deer", "defense", "deficit", "define", "defy", "degree", "delay", "deliver",
    "demand", "demise", "denial", "dentist", "deny", "depart", "depend", "deposit",
    "depth", "deputy", "derive", "describe", "desert", "design", "desk", "despair",
    "destroy", "detail", "detect", "device", "devote", "diagram", "dial", "diamond",
    "diary", "dice", "diesel", "diet", "differ", "digital", "dignity", "dilemma",
    "dinner", "dinosaur", "direct", "dirt", "disagree", "discover", "disease", "dish",
    "dismiss", "disorder", "display", "distance", "divert", "divide", "divorce", "dizzy",
    "doctor", "document", "dog", "doll", "dolphin", "domain", "donate", "donkey",
    "donor", "door", "dose", "double", "dove", "draft", "dragon", "drama",
    "drastic", "draw", "dream", "dress", "drift", "drill", "drink", "drip",
    "drive", "drop", "drum", "dry", "duck", "dumb", "dune", "during",
    "dust", "dutch", "duty", "dwarf", "dynamic", "eager", "eagle", "early",
    "earn", "earth", "easel", "east", "easy", "echo", "eclipse", "ecology",
    "economy", "edge", "edit", "educate", "effort", "eight", "either", "elbow",
    "elder", "electric", "elegant", "element", "elevator", "elite", "elope", "elude",
    "email", "embrace", "emerge", "emotion", "employ", "empower", "empty", "enable",
    "enact", "end", "endless", "endorse", "enemy", "energy", "enforce", "engage",
    "engine", "enhance", "enjoy", "enlist", "enough", "enrich", "enroll", "ensure",
    "enter", "entire", "entry", "envelope", "episode", "equal", "equip", "erase",
    "erode", "erosion", "error", "erupt", "escape", "essay", "estate", "eternal",
    "evade", "evaluate", "even", "event", "every", "evidence", "evil", "evoke",
    "exact", "example", "excess", "exchange", "excite", "exclude", "excuse", "execute",
    "exercise", "exhaust", "exhibit", "exile", "exist", "exit", "exotic", "expand",
    "expect", "expire", "explain", "explicit", "exploit", "explore", "export", "expose",
    "express", "extend", "extra", "eye", "eyebrow", "fabric", "face", "faculty",
    "fade", "faint", "faith", "false", "fame", "family", "famous", "fan",
    "fancy", "fantasy", "farm", "fashion", "fatal", "father", "fatigue", "fault",
    "favorite", "fawn", "feature", "fee", "feedback", "feet", "fence", "festival",
    "fetch", "fever", "fiber", "fiction", "field", "fifteen", "fifth", "fifty",
    "fight", "figure", "file", "film", "filter", "final", "find", "fine",
    "finger", "finish", "fire", "firm", "fiscal", "fish", "fit", "fitness",
    "fix", "flag", "flame", "flap", "flash", "flat", "flavor", "flee",
    "flight", "flip", "float", "flock", "flood", "floor", "flower", "fluid",
    "flush", "fly", "foam", "focus", "fog", "foil", "fold", "follow",
    "food", "foot", "force", "forest", "forget", "fork", "fortune", "forum",
    "forward", "fossil", "foster", "found", "fox", "fragile", "frame", "frequent",
    "fresh", "friend", "fringe", "frog", "front", "frost", "frown", "frozen",
    "fruit", "fuel", "fun", "funny", "furnace", "fury", "future", "gadget",
    "gain", "galaxy", "gallery", "game", "gap", "garage", "garbage", "garden",
    "garlic", "garment", "gas", "gasp", "gate", "gather", "gauge", "gaze",
    "general", "genius", "genre", "gentle", "genuine", "gesture", "ghost", "giant",
    "gift", "giggle", "ginger", "giraffe", "girl", "give", "glad", "glance",
    "glare", "glass", "glide", "glimpse", "globe", "gloom", "glory", "glove",
    "glow", "glue", "goat", "goddess", "gold", "gone", "good", "goose",
    "gorilla", "gospel", "gossip", "govern", "gown", "grab", "grace", "grain",
    "grant", "grape", "grass", "gravity", "great", "green", "grid", "grief",
    "grit", "grocery", "group", "grow", "grudge", "guard", "guess", "guide",
    "guilt", "guitar", "gun", "gym", "habit", "hair", "half", "hammer",
    "hamster", "hand", "happy", "harbor", "hard", "harsh", "harvest", "hat",
    "have", "hawk", "hazard", "head", "heart", "heavy", "hedgehog", "height",
    "hello", "helmet", "help", "hen", "hero", "hip", "hire", "history",
    "hobby", "hockey", "hold", "hole", "holiday", "hollow", "home", "honey",
    "hood", "hope", "horn", "horror", "horse", "hospital", "host", "hotel",
    "hour", "hover", "hub", "huge", "human", "humble", "humor", "hundred",
    "hungry", "hunt", "hurdle", "hurry", "hurt", "husband", "hybrid", "ice",
    "icon", "idea", "identify", "idle", "ignore", "ill", "illegal", "illness",
    "image", "imitate", "immense", "immune", "impact", "impose", "improve", "impulse",
    "inch", "include", "income", "increase", "index", "indicate", "indoor", "industry",
    "infant", "inflict", "inform", "initial", "inject", "inmate", "inner", "innocent",
    "input", "inquiry", "insane", "insect", "inside", "inspire", "install", "intact",
    "interest", "into", "invest", "invite", "involve", "iron", "island", "isolate",
    "issue", "item", "ivory", "jacket", "jaguar", "jar", "jazz", "jealous",
    "jeans", "jelly", "jewel", "job", "join", "joke", "journey", "joy",
    "judge", "juice", "jump", "jungle", "junior", "junk", "just", "kangaroo",
    "keen", "keep", "ketchup", "key", "kick", "kid", "kidney", "kind",
    "kingdom", "kiss", "kit", "kitchen", "kite", "kitten", "kiwi", "knee",
    "knife", "knock", "know", "lab", "label", "labor", "ladder", "lady",
    "lake", "lamp", "language", "laptop", "large", "later", "latin", "laugh",
    "laundry", "lava", "law", "lawn", "lawsuit", "layer", "lazy", "leader",
    "leaf", "learn", "leave", "lecture", "left", "leg", "legal", "legend",
    "leisure", "lemon", "lend", "length", "lens", "leopard", "lesson", "letter",
    "level", "liberty", "library", "license", "life", "lift", "light", "like",
    "limb", "limit", "link", "lion", "liquid", "list", "little", "live",
    "lizard", "load", "loan", "lobster", "local", "lock", "logic", "lonely",
    "long", "loop", "lottery", "loud", "lounge", "love", "loyal", "lucky",
    "luggage", "lumber", "lunar", "lunch", "luxury", "lying", "machine", "mad",
    "magic", "magnet", "maid", "mail", "major", "make", "mammal", "manage",
    "mandate", "mango", "mansion", "manual", "maple", "marble", "march", "margin",
    "marine", "market", "marriage", "mask", "mass", "master", "match", "material",
    "math", "matrix", "matter", "maximum", "maze", "meadow", "mean", "measure",
    "meat", "mechanic", "medal", "media", "melody", "melt", "member", "memory",
    "mention", "menu", "mercy", "merge", "merit", "merry", "mesh", "message",
    "metal", "method", "middle", "midnight", "milk", "million", "mimic", "mind",
    "minimum", "minor", "minute", "miracle", "mirror", "misery", "miss", "mistake",
    "mix", "mixture", "mobile", "model", "modify", "mom", "moment", "monitor",
    "monkey", "monster", "month", "moon", "moral", "more", "morning", "mosquito",
    "mother", "motion", "motor", "mountain", "mouse", "move", "movie", "much",
    "muffin", "mule", "multiply", "muscle", "museum", "mushroom", "music", "must",
    "mutual", "myself", "mystery", "myth", "naive", "name", "napkin", "narrow",
    "nasty", "nation", "nature", "near", "neck", "need", "negative", "neglect",
    "neither", "nephew", "nerve", "nest", "net", "network", "neutral", "never",
    "news", "next", "nice", "night", "noble", "noise", "nominee", "noodle",
    "normal", "north", "nose", "notable", "nothing", "notice", "novel", "now",
    "nuclear", "number", "nurse", "nut", "oak", "obey", "object", "oblige",
    "obscure", "observe", "obtain", "obvious", "occur", "ocean", "october", "odor",
    "off", "offer", "office", "often", "oil", "okay", "old", "olive",
    "olympic", "omit", "once", "one", "onion", "online", "only", "open",
    "opera", "opinion", "oppose", "option", "orange", "orbit", "orchard", "order",
    "ordinary", "organ", "orient", "original", "orphan", "ostrich", "other", "outdoor",
    "outer", "output", "outside", "oval", "oven", "over", "own", "owner",
    "oxygen", "oyster", "ozone", "pact", "paddle", "page", "pair", "palace",
    "palm", "panda", "panel", "panic", "panther", "paper", "parade", "parent",
    "park", "parrot", "party", "pass", "patch", "path", "patient", "patrol",
    "pattern", "pause", "pave", "payment", "peace", "peanut", "pear", "peasant",
    "pelican", "pen", "penalty", "pencil", "people", "pepper", "perfect", "permit",
    "person", "pet", "phone", "photo", "phrase", "physical", "piano", "picnic",
    "picture", "piece", "pig", "pigeon", "pill", "pilot", "pink", "pioneer",
    "pipe", "pistol", "pitch", "pizza", "place", "planet", "plastic", "plate",
    "play", "please", "pledge", "pluck", "plug", "plunge", "poem", "poet",
    "point", "polar", "pole", "police", "pond", "pony", "pool", "popular",
    "portion", "pose", "position", "possible", "post", "potato", "pottery", "poverty",
    "powder", "power", "practice", "praise", "predict", "prefer", "prepare", "present",
    "pretty", "prevent", "price", "pride", "primary", "print", "priority", "prison",
    "private", "prize", "problem", "process", "produce", "profit", "program", "project",
    "promote", "proof", "property", "prosper", "protect", "proud", "provide", "public",
    "pudding", "pull", "pulp", "pulse", "pumpkin", "punch", "pupil", "puppy",
    "purchase", "purity", "purpose", "purse", "push", "put", "puzzle", "pyramid",
    "quality", "quantum", "quarter", "question", "quick", "quit", "quiz", "quote",
    "rabbit", "raccoon", "race", "rack", "radar", "radio", "rage", "rail",
    "rain", "raise", "rally", "ramp", "ranch", "random", "range", "rapid",
    "rare", "rate", "rather", "raven", "raw", "razor", "ready", "real",
    "reason", "rebel", "rebuild", "recall", "receive", "recipe", "record", "recycle",
    "reduce", "reflect", "reform", "region", "regret", "regular", "reject", "relax",
    "release", "relief", "rely", "remain", "remedy", "remind", "remote", "remove",
    "render", "renew", "rent", "reopen", "repair", "repeat", "replace", "report",
    "require", "rescue", "resemble", "resist", "resource", "response", "result", "retire",
    "retreat", "return", "reunion", "reveal", "review", "reward", "rhythm", "rib",
    "ribbon", "rice", "rich", "ride", "ridge", "rifle", "right", "rigid",
    "ring", "riot", "ripple", "risk", "ritual", "rival", "river", "road",
    "roast", "robin", "robot", "robust", "rocket", "romance", "roof", "rookie",
    "room", "rose", "rotate", "rough", "round", "route", "royal", "rubber",
    "rude", "rug", "rule", "run", "runway", "rural", "sad", "saddle",
    "sadness", "safe", "sail", "salad", "salmon", "salon", "salt", "salute",
    "same", "sample", "sand", "satisfy", "satoshi", "sauce", "sausage", "save",
    "say", "scale", "scan", "scare", "scatter", "scene", "scheme", "school",
    "science", "scissors", "scorpion", "scout", "scrap", "screen", "script", "scrub",
    "sea", "search", "season", "seat", "second", "secret", "section", "security",
    "seed", "seek", "segment", "select", "sell", "seminar", "senior", "sense",
    "sentence", "series", "service", "session", "settle", "setup", "seven", "shadow",
    "shaft", "shallow", "share", "shed", "shell", "sheriff", "shield", "shift",
    "shine", "ship", "shiver", "shock", "shoe", "shoot", "shop", "short",
    "shoulder", "shove", "shrimp", "shrug", "shuffle", "shy", "sibling", "sick",
    "side", "siege", "sight", "sign", "silent", "silk", "silly", "silver",
    "similar", "simple", "since", "sing", "siren", "sister", "situate", "sixteen",
    "size", "skate", "sketch", "ski", "skill", "skin", "skirt", "skull",
    "slab", "slam", "sleep", "slender", "slice", "slide", "slight", "slim",
    "slogan", "slot", "slow", "slush", "small", "smart", "smile", "smoke",
    "smooth", "snack", "snake", "snap", "sniff", "snow", "soap", "soccer",
    "social", "sock", "soda", "soft", "solar", "soldier", "solid", "solution",
    "solve", "someone", "song", "soon", "sorry", "sort", "soul", "sound",
    "soup", "source", "south", "space", "spare", "spatial", "spawn", "speak",
    "special", "speed", "spell", "spend", "sphere", "spice", "spider", "spike",
    "spin", "spirit", "split", "sponsor", "spoon", "sport", "spot", "spray",
    "spread", "spring", "spy", "square", "squeeze", "squirrel", "stable", "stadium",
    "staff", "stage", "stairs", "stamp", "stand", "start", "state", "stay",
    "steak", "steel", "stem", "step", "stereo", "stick", "still", "sting",
    "stock", "stomach", "stone", "stool", "story", "stove", "strategy", "street",
    "strike", "strong", "struggle", "student", "stuff", "stumble", "style", "subject",
    "submit", "subway", "success", "such", "sudden", "suffer", "sugar", "suggest",
    "suit", "summer", "sun", "sunny", "sunset", "super", "supply", "supreme",
    "sure", "surface", "surge", "surprise", "surround", "survey", "suspect", "sustain",
    "swallow", "swamp", "swap", "swarm", "swear", "sweet", "swim", "swing",
    "switch", "sword", "symbol", "symptom", "syrup", "system", "table", "tackle",
    "tag", "tail", "talent", "talk", "tank", "tape", "target", "task",
    "taste", "tattoo", "taxi", "teach", "team", "tell", "ten", "tenant",
    "tennis", "tent", "term", "test", "text", "thank", "that", "theme",
    "then", "theory", "there", "they", "thing", "this", "thought", "three",
    "thrive", "throw", "thumb", "thunder", "ticket", "tide", "tiger", "tilt",
    "timber", "time", "tiny", "tip", "tired", "tissue", "title", "toast",
    "tobacco", "today", "toddler", "toe", "together", "toilet", "token", "tomato",
    "tomorrow", "tone", "tongue", "tonight", "tool", "tooth", "top", "topic",
    "topple", "torch", "tornado", "tortoise", "toss", "total", "tourist", "toward",
    "tower", "town", "toy", "track", "trade", "traffic", "tragic", "train",
    "transfer", "trap", "trash", "travel", "tray", "treat", "tree", "trend",
    "trial", "tribe", "trick", "trigger", "trim", "trip", "trophy", "trouble",
    "truck", "true", "truly", "trumpet", "trust", "truth", "try", "tube",
    "tuna", "tunnel", "turkey", "turn", "turtle", "twelve", "twenty", "twice",
    "twin", "twist", "two", "type", "typical", "ugly", "umbrella", "unable",
    "unaware", "uncle", "uncover", "under", "undo", "unfair", "unfold", "unhappy",
    "uniform", "union", "unique", "unit", "universe", "unknown", "unlock", "until",
    "unusual", "unveil", "update", "upgrade", "upon", "upper", "upset", "urban",
    "usage", "use", "used", "useful", "useless", "usual", "utility", "vacant",
    "vacuum", "vague", "valid", "valley", "valve", "van", "vanish", "vapor",
    "various", "vast", "vault", "vehicle", "velvet", "vendor", "venture", "venue",
    "verb", "verify", "version", "very", "vessel", "veteran", "viable", "vibrant",
    "vicious", "victory", "video", "view", "village", "vintage", "violin", "virtual",
    "virus", "visa", "visit", "visual", "vital", "vivid", "vocal", "voice",
    "void", "volcano", "volume", "vote", "voyage", "wage", "wagon", "wait",
    "walk", "wall", "walnut", "want", "warfare", "warm", "warrior", "wash",
    "wasp", "waste", "water", "wave", "way", "wealth", "weapon", "wear",
    "weasel", "weather", "web", "wedding", "weekend", "weird", "welcome", "well",
    "west", "western", "wet", "whale", "what", "wheat", "wheel", "when",
    "where", "whip", "whisper", "wide", "width", "wife", "wild", "will",
    "win", "window", "wine", "wing", "wink", "winner", "winter", "wire",
    "wisdom", "wise", "wish", "witness", "wolf", "woman", "wonder", "wood",
    "wool", "word", "work", "world", "worry", "worth", "wrap", "wreck",
    "wrestle", "wrist", "write", "wrong", "yard", "year", "yellow", "young",
    "youth", "zebra", "zero", "zone", "zoo"
];

/// Generate a random passphrase.
pub fn generate_passphrase(options: &PassphraseOptions) -> String {
    let mut rng = rand::thread_rng();
    
    let words: Vec<String> = (0..options.word_count)
        .map(|_| {
            let word = WORDLIST.choose(&mut rng).unwrap_or(&"error");
            if options.capitalize {
                let mut chars = word.chars();
                match chars.next() {
                    None => String::new(),
                    Some(c) => c.to_uppercase().to_string() + chars.as_str(),
                }
            } else {
                word.to_string()
            }
        })
        .collect();
    
    words.join(&options.separator.to_string())
}
